In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
import numpy as np
pd.set_option('display.float_format', '{:.6f}'.format)
pd.set_option('display.float_format', lambda x: "{:.6f}".format(x) if not pd.isna(x) else "NaN")

In [2]:
data=pd.read_csv("updated_Entire_Reference.csv",encoding='ISO-8859-1',low_memory=False)


In [3]:
data.head(2)

Unique_id  district_id_x  Temporary_ID_x  family_id  village_ward_id_x  \
0  100686666              1          686666   30117241             107579   
1  101094169              1         1094169   20257923             107874   

   NPR_member_code  samagra_code    first_name_x    last_name_x  \
0              NaN           NaN          Barsha          Rajak   
1              NaN           NaN  Deleted-Gurnam  Singh Bairagi   

                          first_name_Hi  \
0        बर्शा   
1  गुरनाम   

                                        last_name_Hi  is_head  gender_id  \
0                                 रजक        0          2   
1  सिंह बैरàÂ...        0          1   

          dob  relation_id  marital_status_id  father_id  mother_id  \
0  01-01-2001            4                  2          0  141513241   
1  01-01-1948            0                  2          0          0   

         spouse_id father_name_x   mother_name spouse_name  mobile_number  \
0 141518229.000000           NaN  Geeta Dhobee      Ankesh            NaN   
1              NaN        Gumjar           NaN         NaN            NaN   

   email_address  education_status_id  educational_institution_type_id  \
0            NaN             1.000000                         1.000000   
1            NaN             2.000000                         2.000000   

   class_in_school  school_details  School_Type  profession_id  is_disabled  \
0         5.000000  govt jhundpura     3.000000       0.000000            0   
1              NaN             NaN          NaN       0.000000            0   

   annual_income  nirashrit_before_2007_nonBPL  Aadhaar_status_id  \
0       0.000000                           NaN                NaN   
1  200000.000000                           NaN                NaN   

   Aadhaar_Enrollment_No  is_updated_x  Verified_By       Verified_On  \
0                    NaN      1.000000   765.000000  01-09-2013 10:11   
1                    NaN      1.000000 52296.000000  28-10-2013 17:19   

   is_destitute  is_active  is_locked_x  is_Death  is_deleted_x  \
0           NaN        NaN          NaN         0             0   
1           NaN   1.000000          NaN         0             0   

   Approve_Status_x  Import_phase     insert_time_x update_time  \
0               NaN             0  29-01-2013 15:02         NaN   
1               NaN             0  01-02-2013 20:25         NaN   

   inserted_by_user_id  enc_aadhaar_id  Whats_Up_Mobile_No  category_id_x  \
0                 4870             NaN                 NaN              3   
1                 1150             NaN                 NaN              3   

   lbverified  dormant  Member_Ekyc Middle_Name  Middle_Name_HI  IS_suspect  \
0           1        0          NaN         NaN             NaN         NaN   
1           1        0          NaN         NaN             NaN         NaN   

                     FullNameEn  \
0                  Barsha Rajak   
1  Deleted-Gurnam Singh Bairagi   

                                          FullNameHi caste      id_y  \
0  बर्शा रजक   NaN  30117241   
1  गुरनाम सàÂ...   NaN  20257923   

   district_id_y  Temporary_ID_y  village_ward_id_y  Gadna_Block_ID  House_No  \
0              1        0.000000             107579       79.000000       368   
1              1        0.000000             107874      256.000000         1   

   House_No_Section House_Address house_hold_number  npr_family_code  \
0          0.000000     Heerapura               NaN              NaN   
1          0.000000       Kalarna               NaN              NaN   

   pin_code  member_count  head_family_member_id  category_id_y  \
0    476335             6       141510564.000000              3   
1    476337             0       101096478.000000              3   

   Category_Cod

## Creating the First Key first name,  surname, family id and father id over here

In [4]:
data['family_id']

0       30117241
1       20257923
2       20259742
3       20259742
4       28016000
          ...   
1029    20002907
1030    42038346
1031    20297764
1032    20310063
1033    20317161
Name: family_id, Length: 1034, dtype: int64

In [5]:
data['first_name_x']

0               Barsha
1       Deleted-Gurnam
2       Shambhoo Singh
3              SUGREEV
4               jamila
             ...      
1029        Dharmendra
1030             RAJNI
1031            Pallvi
1032          divyansh
1033            Preeti
Name: first_name_x, Length: 1034, dtype: object

In [6]:
data['last_name_x']

0               Rajak
1       Singh Bairagi
2              Gurjar
3              GURJAR
4               saify
            ...      
1029            Malvi
1030          PARIHAR
1031           Baghel
1032            meena
1033            Regar
Name: last_name_x, Length: 1034, dtype: object

In [7]:
data['father_id']

0               0
1               0
2               0
3       101099177
4       101142719
          ...    
1029    100002994
1030    101239082
1031    101255164
1032    101306507
1033    101334568
Name: father_id, Length: 1034, dtype: int64

In [8]:
first_name = data['first_name_x'].astype(str).str.strip()
last_name = data['last_name_x'].astype(str).str.strip()
family_id = data['family_id'].astype(str).str.strip()
father_id = data['father_id'].astype(str).str.strip()

In [9]:
data['UniqueKey1'] = first_name + last_name + family_id + father_id

In [10]:
data['UniqueKey1'] = data['UniqueKey1'].str.replace(r'\s+', '', regex=True)

In [11]:
data['UniqueKey1'].value_counts()

BarshaRajak301172410               1
ANANNYASHARMA20439556101833196     1
RamSwaroopJatav204290460           1
YashmenMohamad20428845101788411    1
GobariBai204290460                 1
                                  ..
RamfoolBatham203892970             1
MOHITLOUDHA20387171101626990       1
JyotiBatham20389297101629695       1
MahimaLoudha20387171101626990      1
PreetiRegar20317161101334568       1
Name: UniqueKey1, Length: 1034, dtype: int64

In [12]:
len(data['UniqueKey1'].unique())

1034

## Creating the second unique key over here first_name, last_name, father name, mother name, gender, village name, village code, block name and block code, district name and district code,mobile number and aadhaar number.

In [13]:
data['first_name_x']

0               Barsha
1       Deleted-Gurnam
2       Shambhoo Singh
3              SUGREEV
4               jamila
             ...      
1029        Dharmendra
1030             RAJNI
1031            Pallvi
1032          divyansh
1033            Preeti
Name: first_name_x, Length: 1034, dtype: object

In [14]:
data['last_name_x']

0               Rajak
1       Singh Bairagi
2              Gurjar
3              GURJAR
4               saify
            ...      
1029            Malvi
1030          PARIHAR
1031           Baghel
1032            meena
1033            Regar
Name: last_name_x, Length: 1034, dtype: object

In [15]:
data['father_name_x']

0                         NaN
1                      Gumjar
2                         NaN
3       Shambhoo Singh Gurjar
4                   tahir ali
                ...          
1029        Phoolchand Gehlod
1030             Raju Parihar
1031    Brajesh  Kumar Baghel
1032          nar singh meena
1033              Puran Regar
Name: father_name_x, Length: 1034, dtype: object

In [16]:
data['mother_name']

0                 Geeta Dhobee
1                          NaN
2                          NaN
3                     Dodi Bai
4                  husaina bai
                 ...          
1029    Sulochana Bai Fulsingh
1030                    Mamta 
1031             Prabha Baghal
1032                       NaN
1033              Laxmi Regare
Name: mother_name, Length: 1034, dtype: object

In [17]:
data['Gender']

0       Female
1         Male
2         Male
3         Male
4       Female
         ...  
1029      Male
1030    Female
1031    Female
1032      Male
1033    Female
Name: Gender, Length: 1034, dtype: object

In [18]:
data['Village'].value_counts()

BHONSLEGAON    1
bhonslegao     1
Name: Village, dtype: int64

In [19]:
data['village_code'].unique()

array([    nan, 114381., 107857., 107546., 107447., 107601.,  92590.])

In [20]:
data['Block'].unique()

array([nan, 'Ashoknagar'], dtype=object)

In [21]:
data['BlockCode'].unique()

array([ nan, 156.])

In [22]:
data['District_Name'].unique()

array(['SHEOPUR', 'BETUL', 'ASHOKNAGAR', 'UMARIA', 'DINDORI', 'GWALIOR',
       'NARMADAPURAM', 'VIDISHA', 'RAISEN', 'DEWAS'], dtype=object)

In [23]:
data['district_id_x'].unique()

array([ 1, 35, 46, 15, 41,  4, 37, 31, 34, 23], dtype=int64)

In [24]:
data['mobile_number'].value_counts()

7880261883.000000    4
7415355123.000000    3
9752139676.000000    2
8349340737.000000    2
9926263926.000000    1
                    ..
8462876051.000000    1
7440746178.000000    1
6267124447.000000    1
7271802287.000000    1
8120745413.000000    1
Name: mobile_number, Length: 138, dtype: int64

In [25]:
data['AadharRefrenceNo'].unique()

array([     nan, 4.59e+17, 3.37e+17, 8.31e+17, 6.44e+17, 4.62e+17,
       5.76e+17, 1.90e+17, 5.16e+17, 1.93e+17, 2.21e+17, 3.05e+17,
       4.68e+17])

In [26]:
df=data

In [27]:
first_name = df['first_name_x'].astype(str).str.strip()
last_name = df['last_name_x'].astype(str).str.strip()
father_name = df['father_name_x'].astype(str).str.strip()
mother_name = df['mother_name'].astype(str).str.strip()
gender = df['Gender'].astype(str).str.strip()
village = df['Village'].astype(str).str.strip()
village_code = df['village_code'].astype(str).str.strip()
block = df['Block'].astype(str).str.strip()
block_code = df['BlockCode'].astype(str).str.strip()
district_name = df['District_Name'].astype(str).str.strip()
district_id = df['district_id_x'].astype(str).str.strip()
mobile_number = df['mobile_number'].astype(str).str.strip()
aadhar_ref_no = df['AadharRefrenceNo'].astype(str).str.strip()

In [28]:
df['UniqueKey2'] = first_name + last_name + father_name + mother_name + gender + village + village_code + block + block_code + district_name + district_id + mobile_number + aadhar_ref_no

In [29]:
df['UniqueKey2'].value_counts()

ReenaSinghnannanFemalenannannannanSHEOPUR1nannan                               2
BarshaRajaknanGeeta DhobeeFemalenannannannanSHEOPUR1nannan                     1
AshaJatavDevishankar jatavDwarika BaiFemalenannannannanSHEOPUR1nannan          1
NaitikBalmikiVijay ValmikMamta BaiMalenannannannanSHEOPUR1nannan               1
PoonamBaimikiVijay ValmikMamta BaiFemalenannannannanSHEOPUR1nannan             1
                                                                              ..
RamfoolBathamTejmalnanMalenannannannanSHEOPUR18462876051.0nan                  1
MOHITLOUDHAVinod LoudhaSheela LodhaMalenannannannanSHEOPUR1nannan              1
JyotiBathamRamfool BathamSita BaiFemalenannannannanSHEOPUR1nannan              1
MahimaLoudhaVinod LoudhaSheela LodhaFemalenannannannanSHEOPUR1nannan           1
PreetiRegarPuran RegarLaxmi RegareFemalenannannannanSHEOPUR18120745413.0nan    1
Name: UniqueKey2, Length: 1033, dtype: int64

In [30]:
df['UniqueKey2'] = df['UniqueKey2'].str.replace(r'\s+', '', regex=True)

In [31]:
data['UniqueKey2'].unique()

array(['BarshaRajaknanGeetaDhobeeFemalenannannannanSHEOPUR1nannan',
       'Deleted-GurnamSinghBairagiGumjarnanMalenannannannanSHEOPUR1nannan',
       'ShambhooSinghGurjarnannanMalenannannannanSHEOPUR1nannan', ...,
       'PallviBaghelBrajeshKumarBaghelPrabhaBaghalFemalenannannannanSHEOPUR17224958635.0nan',
       'divyanshmeenanarsinghmeenananMalenannannannanSHEOPUR19977441258.0nan',
       'PreetiRegarPuranRegarLaxmiRegareFemalenannannannanSHEOPUR18120745413.0nan'],
      dtype=object)

In [32]:
data.head(2)

Unique_id  district_id_x  Temporary_ID_x  family_id  village_ward_id_x  \
0  100686666              1          686666   30117241             107579   
1  101094169              1         1094169   20257923             107874   

   NPR_member_code  samagra_code    first_name_x    last_name_x  \
0              NaN           NaN          Barsha          Rajak   
1              NaN           NaN  Deleted-Gurnam  Singh Bairagi   

                          first_name_Hi  \
0        बर्शा   
1  गुरनाम   

                                        last_name_Hi  is_head  gender_id  \
0                                 रजक        0          2   
1  सिंह बैरàÂ...        0          1   

          dob  relation_id  marital_status_id  father_id  mother_id  \
0  01-01-2001            4                  2          0  141513241   
1  01-01-1948            0                  2          0          0   

         spouse_id father_name_x   mother_name spouse_name  mobile_number  \
0 141518229.000000           NaN  Geeta Dhobee      Ankesh            NaN   
1              NaN        Gumjar           NaN         NaN            NaN   

   email_address  education_status_id  educational_institution_type_id  \
0            NaN             1.000000                         1.000000   
1            NaN             2.000000                         2.000000   

   class_in_school  school_details  School_Type  profession_id  is_disabled  \
0         5.000000  govt jhundpura     3.000000       0.000000            0   
1              NaN             NaN          NaN       0.000000            0   

   annual_income  nirashrit_before_2007_nonBPL  Aadhaar_status_id  \
0       0.000000                           NaN                NaN   
1  200000.000000                           NaN                NaN   

   Aadhaar_Enrollment_No  is_updated_x  Verified_By       Verified_On  \
0                    NaN      1.000000   765.000000  01-09-2013 10:11   
1                    NaN      1.000000 52296.000000  28-10-2013 17:19   

   is_destitute  is_active  is_locked_x  is_Death  is_deleted_x  \
0           NaN        NaN          NaN         0             0   
1           NaN   1.000000          NaN         0             0   

   Approve_Status_x  Import_phase     insert_time_x update_time  \
0               NaN             0  29-01-2013 15:02         NaN   
1               NaN             0  01-02-2013 20:25         NaN   

   inserted_by_user_id  enc_aadhaar_id  Whats_Up_Mobile_No  category_id_x  \
0                 4870             NaN                 NaN              3   
1                 1150             NaN                 NaN              3   

   lbverified  dormant  Member_Ekyc Middle_Name  Middle_Name_HI  IS_suspect  \
0           1        0          NaN         NaN             NaN         NaN   
1           1        0          NaN         NaN             NaN         NaN   

                     FullNameEn  \
0                  Barsha Rajak   
1  Deleted-Gurnam Singh Bairagi   

                                          FullNameHi caste      id_y  \
0  बर्शा रजक   NaN  30117241   
1  गुरनाम सàÂ...   NaN  20257923   

   district_id_y  Temporary_ID_y  village_ward_id_y  Gadna_Block_ID  House_No  \
0              1        0.000000             107579       79.000000       368   
1              1        0.000000             107874      256.000000         1   

   House_No_Section House_Address house_hold_number  npr_family_code  \
0          0.000000     Heerapura               NaN              NaN   
1          0.000000       Kalarna               NaN              NaN   

   pin_code  member_count  head_family_member_id  category_id_y  \
0    476335             6       141510564.000000              3   
1    476337             0       101096478.000000              3   

   Category_Cod

In [33]:
list(data.columns)

['Unique_id',
 'district_id_x',
 'Temporary_ID_x',
 'family_id',
 'village_ward_id_x',
 'NPR_member_code',
 'samagra_code',
 'first_name_x',
 'last_name_x',
 'first_name_Hi',
 'last_name_Hi',
 'is_head',
 'gender_id',
 'dob',
 'relation_id',
 'marital_status_id',
 'father_id',
 'mother_id',
 'spouse_id',
 'father_name_x',
 'mother_name',
 'spouse_name',
 'mobile_number',
 'email_address',
 'education_status_id',
 'educational_institution_type_id',
 'class_in_school',
 'school_details',
 'School_Type',
 'profession_id',
 'is_disabled',
 'annual_income',
 'nirashrit_before_2007_nonBPL',
 'Aadhaar_status_id',
 'Aadhaar_Enrollment_No',
 'is_updated_x',
 'Verified_By',
 'Verified_On',
 'is_destitute',
 'is_active',
 'is_locked_x',
 'is_Death',
 'is_deleted_x',
 'Approve_Status_x',
 'Import_phase',
 'insert_time_x',
 'update_time',
 'inserted_by_user_id',
 'enc_aadhaar_id',
 'Whats_Up_Mobile_No',
 'category_id_x',
 'lbverified',
 'dormant',
 'Member_Ekyc',
 'Middle_Name',
 'Middle_Name_HI',


In [34]:
data['mobile_number']

0                    NaN
1                    NaN
2                    NaN
3                    NaN
4                    NaN
              ...       
1029                 NaN
1030                 NaN
1031   7224958635.000000
1032   9977441258.000000
1033   8120745413.000000
Name: mobile_number, Length: 1034, dtype: float64

In [35]:
df.shape

(1034, 390)

In [36]:
data.shape

(1034, 390)

## Check same mobile number tagged to multiple names

In [37]:
from fuzzywuzzy import fuzz
import pandas as pd

# Assuming you have a DataFrame called df with columns 'FullNameEn' and 'mobile_number'

# Function to check if two names are similar
def are_names_similar(name1, name2):
    # You can adjust the threshold according to your requirements
    similarity_ratio = fuzz.token_sort_ratio(name1, name2)
    return similarity_ratio > 59  # Adjust threshold as needed

# Grouping by mobile number and checking for duplicate names
grouped = df.groupby('mobile_number')['FullNameEn'].apply(list)

# Initialize a list to store the results
duplicates = []

# Iterate through each group
for mobile, names in grouped.iteritems():
    # If there's only one name associated with the mobile number, skip
    if len(names) <= 1:
        continue
    
    # Iterate through pairs of names to check for similarity
    for i in range(len(names)):
        for j in range(i + 1, len(names)):
            if are_names_similar(names[i], names[j]):
                # If the names are similar, consider it a duplicate
                duplicates.append({'mobile_number': mobile, 'name1': names[i], 'name2': names[j]})

# Convert the list of duplicates to a DataFrame
duplicates_df = pd.DataFrame(duplicates)
duplicates_df

C:\Users\Admin\AppData\Local\Temp\ipykernel_8132\1861349483.py:19: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for mobile, names in grouped.iteritems():


mobile_number           name1            name2
0 7415355123.000000  Jiyoti Solanki  Megraaj Solanki
1 7880261883.000000       Payal Bai        Sapna Bai
2 7880261883.000000       Payal Bai      Kanchan Bai
3 7880261883.000000       Sapna Bai      Kanchan Bai
4 8349340737.000000   Gaura Ahirwar    Pooja Ahirwar

In [38]:
df['dob'].unique()

array(['01-01-2001', '01-01-1948', '01-01-1970', '26-06-1996',
       '10-08-1993', '01-01-1977', '01-07-1998', '09-04-2003',
       '12-05-2005', '01-01-1984', '01-01-1995', '01-01-1998',
       '01-01-1985', '01-07-1960', '01-01-1980', '01-01-1986',
       '01-01-1992', '01-01-1950', '01-01-1967', '01-01-1981',
       '22-02-2007', '01-07-2009', '01-01-2011', '15-11-2012',
       '01-01-1993', '01-01-2000', '01-01-2009', '01-01-1990',
       '01-01-1997', '01-07-1994', '01-01-1999', '01-01-1935',
       '01-01-1976', '01-02-2003', '07-07-2006', '01-07-1973',
       '01-07-1976', '18-10-2006', '04-05-2004', '01-07-2006',
       '01-07-1967', '01-01-1996', '02-03-1943', '01-07-1978',
       '17-11-2000', '01-07-1990', '04-07-1977', '31-05-2004',
       '16-05-2006', '02-08-2008', '25-01-1970', '01-07-1986',
       '01-07-1982', '01-07-2005', '01-01-1987', '30-11-2012',
       '01-07-1988', '01-01-2007', '03-06-2007', '02-05-1985',
       '02-02-2008', '15-07-2003', '20-06-2003', '12-06

In [39]:
df['DOB_x'].unique()

array([nan, '01-01-1999', '01-01-1989', '01-01-1978', '01-06-1997',
       '01-01-1976', '01-01-2002', '01-01-1975', '01-01-1974',
       '01-01-1977', '01-01-1991', '01-01-1963', '30-11-2001',
       '30-08-1993'], dtype=object)

In [40]:
df['DOB_y'].unique()

array([nan, '01-01-1988', '03-04-1975'], dtype=object)

In [41]:
df['annual_income'].unique()

array([0.00e+00, 2.00e+05, 6.50e+04, 7.00e+03, 6.00e+03, 4.00e+04,
       8.00e+03, 1.20e+04, 1.00e+04, 3.30e+03, 5.00e+03, 2.40e+03,
       9.00e+03, 1.50e+05, 3.60e+04,      nan, 3.00e+04, 2.00e+04,
       1.00e+02, 2.50e+04, 1.10e+04, 1.50e+04, 2.40e+05, 3.00e+03,
       4.00e+03, 1.80e+03, 1.08e+05, 2.80e+04, 6.00e+04, 1.20e+05,
       1.00e+03, 4.80e+04, 1.00e+05, 8.40e+04, 5.00e+04, 1.40e+05,
       1.80e+05, 8.00e+04, 2.40e+04, 2.50e+06, 2.50e+05, 7.20e+04,
       3.00e+05, 1.80e+04, 1.60e+05, 5.00e+05, 1.30e+05, 7.00e+04,
       1.10e+05, 1.90e+05, 3.50e+05, 3.40e+05, 2.20e+04, 3.60e+05,
       4.20e+05, 2.80e+05])

In [42]:
df['Annual_Income'].unique()

array([    nan,  40000.,  30000., 680514., 200000.,  20000.])

In [43]:
df.to_csv("15May2024_ReferenceData.csv",index=False)

## On name, apply fuzzy logic and label as perfect duplicate and potential duplicate

In [44]:
import csv
import pandas as pd
from fuzzywuzzy import fuzz

# Function to read data from CSV file
def read_data_from_csv(file_path):
    data = []
    with open(file_path, newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            data.append(row)
    return data


source_csv_path = 'Family_Member.csv'
reference_csv_path = '15May2024_ReferenceData.csv'

source_data = read_data_from_csv(source_csv_path)
reference_data = read_data_from_csv(reference_csv_path)

def fuzzy_match_records(source_record, reference_records, threshold=90):
    matches = []
    for ref_record in reference_records:
        name_similarity = fuzz.token_sort_ratio(source_record["FullNameEn"], ref_record["FullNameEn"])
        if name_similarity >= threshold:
            matches.append({
                'BaseData': source_record,
                'ReferenceData': ref_record,
                'NameSimilarity': name_similarity
            })
    return matches

matches = []
for source_record in source_data:
    matches.extend(fuzzy_match_records(source_record, reference_data))

matched_df = pd.DataFrame(matches)

# Add indicator column
matched_df['DuplicateType'] = matched_df.apply(lambda x: 'Perfect Duplicate' if x['BaseData']['FullNameEn'] == x['ReferenceData']['FullNameEn'] else 'Potential Duplicate', axis=1)

# Save matched results to CSV
matched_df.to_csv('matched_results_fuzzywuzzy.csv', index=False)

# Print matched records
for index, match in matched_df.iterrows():
    print("Base Data:")
    print(match['BaseData'])
    print("Reference Data:")
    print(match['ReferenceData'])
    print("Name Similarity:", match['NameSimilarity'])
    print("Duplicate Type:", match['DuplicateType'])
    print()


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

